<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QANR90JHUTD" name="com.qbr.TestSteps.LoginTest" tests="1" failures="0" timestamp="12 Jun 2018 05:23:03 GMT" time="36.722" errors="1">
  <testcase name="negativeLoginTest" time="36.722" classname="com.qbr.TestSteps.LoginTest">
    <error type="java.lang.AssertionError" message="Login Err Msg different. 
Expected:Oops! The login details you entered do not match our records.
Actual:Unfortunately the system is unavailable at this time. Please try again later, or if the matter is urgent you may contact the Qantas Business Rewards Service Centre on 13 74 78. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Err Msg different. 
Expected:Oops! The login details you entered do not match our records.
Actual:Unfortunately the system is unavailable at this time. Please try again later, or if the matter is urgent you may contact the Qantas Business Rewards Service Centre on 13 74 78. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.qbr.TestSteps.LoginTest.negativeLoginTest(LoginTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- negativeLoginTest -->
</testsuite> <!-- com.qbr.TestSteps.LoginTest -->
